export const paths = {
  LOGIN: "login",
  REGISTER: "register",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  ADMIN: "admin",
  STUDENT: "student",
  STUDENT_LESSONS: "lessons",
  STUDENT_LESSON_READ: "lessons/:lessonSlug",
  STUDENT_PATH: "path",
  STUDENT_VOCAB: "vocab",
  STUDENT_PROFILE: "profile",
  STUDENT_LEADERBOARD: "leaderboard",
  SCHEDULE: "schedule",
  STUDENTS_NEED_SUPPORT: "students-need-support",
  MANAGE_USER: "manage-user",
  MANAGE_ROLE: "manage-role",
  MANAGE_CLASSROOM: "manage-classroom",
  MANAGE_SUBJECT: "manage-subject",
  MANAGE_ENROLLMENT: "manage-enrollment",
  MANAGE_LESSON: "manage-lesson",
  MANAGE_QUESTIONS: "questions",
  MANAGE_VOCABULARY_WORDS: "vocabulary-words",
  MANAGE_VOCABULARY_SETS: "vocabulary-sets",
  MANAGE_SYSTEM_CONFIG: "system-config",
  LESSON_EDITOR: "manage-lesson/:lessonId/edit",
  REVIEW_DOC: "review-doc",
  AI_ASSISTANT: "ai-assistant",
  USAGE_GUIDE: "huong-dan",
} as const;

/** Absolute paths for student zone routing & links. */
export const studentRoutePaths = {
  home: `/${paths.STUDENT}`,
  lessons: `/${paths.STUDENT}/${paths.STUDENT_LESSONS}`,
  lessonRead: (lessonSlug: string) => `/${paths.STUDENT}/lessons/${lessonSlug}`,
  path: `/${paths.STUDENT}/${paths.STUDENT_PATH}`,
  vocab: `/${paths.STUDENT}/${paths.STUDENT_VOCAB}`,
  vocabSet: (setId: string) => `/${paths.STUDENT}/${paths.STUDENT_VOCAB}/${setId}`,
  profile: `/${paths.STUDENT}/${paths.STUDENT_PROFILE}`,
  leaderboard: `/${paths.STUDENT}/${paths.STUDENT_LEADERBOARD}`,
  usageGuide: `/${paths.STUDENT}/${paths.USAGE_GUIDE}`,
} as const;
